
******************************************************************
*
*  Copyright © 2001 TangoWare
*
*  TangoWare
*  19 David Drive                                
*  Belmont, NH  03220
*
*  This computer program is protected by copyright law and 
*  international treaties.  No part of this program may be 
*  reproduced or transmitted in any form or by any means, 
*  electronic or mechanical, for any purpose, without the 
*  express written permission of TangoWare.  
*  Unauthorized reproduction or distribution of this program, 
*  or any portion of it, may result in severe civil and 
*  criminal penalties, and will be prosecuted to the maximum 
*  extent possible under the law.
*
*  Program: PWAITMB.PRG
*
*  Author:  Peter Ryder
*
*  Created: 07/16/2001
*
******************************************************************

